import { posix } from "node:path";

import { canonicalText } from "./canonicalization.mjs";
import { fail } from "./errors.mjs";

function validateConceptPath(path) {
  if (typeof path !== "string" || !path.endsWith(".md") || path.startsWith("/") || path.includes("\\")) {
    fail("KDLC_INDEX_PATH_INVALID", `Invalid concept path: ${path}`);
  }
  const normalized = posix.normalize(path);
  if (normalized !== path || normalized.split("/").some((part) => part === "..") || ["index.md", "log.md"].includes(posix.basename(path))) {
    fail("KDLC_INDEX_PATH_INVALID", `Unsafe or reserved concept path: ${path}`);
  }
}

function markdownText(value) {
  return value.normalize("NFC").replace(/[\[\]\\]/g, "\\$&").replace(/\s+/g, " ").trim();
}

function directoryTitle(path) {
  if (!path) return "Knowledge Index";
  return posix.basename(path).split(/[-_]/).filter(Boolean).map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join(" ");
}

function compareText(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

export function generateHierarchicalIndexes(concepts) {
  const seen = new Set();
  const byDirectory = new Map([["", { concepts: [], children: new Set() }]]);
  for (const concept of concepts) {
    validateConceptPath(concept.path);
    if (seen.has(concept.path)) fail("KDLC_DUPLICATE_CONCEPT", `Duplicate concept path: ${concept.path}`);
    seen.add(concept.path);
    const directory = posix.dirname(concept.path) === "." ? "" : posix.dirname(concept.path);
    if (!byDirectory.has(directory)) byDirectory.set(directory, { concepts: [], children: new Set() });
    byDirectory.get(directory).concepts.push({
      path: concept.path,
      title: markdownText(concept.title || posix.basename(concept.path, ".md")),
      description: concept.description ? markdownText(concept.description) : ""
    });
    let child = directory;
    while (child) {
      const parent = posix.dirname(child) === "." ? "" : posix.dirname(child);
      if (!byDirectory.has(parent)) byDirectory.set(parent, { concepts: [], children: new Set() });
      byDirectory.get(parent).children.add(posix.basename(child));
      child = parent;
    }
  }

  const output = new Map();
  for (const [directory, entries] of [...byDirectory].sort(([a], [b]) => compareText(a, b))) {
    const rows = [
      ...entries.concepts.map((concept) => ({
        title: concept.title,
        path: posix.relative(directory || ".", concept.path),
        description: concept.description
      })),
      ...[...entries.children].map((child) => ({ title: directoryTitle(child), path: `${child}/`, description: "" }))
    ].sort((left, right) => compareText(left.title.normalize("NFC").toLowerCase(), right.title.normalize("NFC").toLowerCase()) || compareText(left.path, right.path));
    const lines = ["<!-- generated by kdlc; do not edit -->", `# ${directoryTitle(directory)}`, ""];
    for (const row of rows) lines.push(`* [${row.title}](${row.path})${row.description ? ` - ${row.description}` : ""}`);
    output.set(directory ? `${directory}/index.md` : "index.md", canonicalText(lines.join("\n")));
  }
  return output;
}
