import { lstat, mkdir, realpath, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";

import { canonicalText } from "./canonicalization.mjs";
import { fail } from "./errors.mjs";

function quoted(value) {
  return JSON.stringify(value.normalize("NFC"));
}

function validateProjectName(name) {
  if (typeof name !== "string" || name.length > 63 || !/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(name)) fail("KDLC_PROJECT_NAME_INVALID", `Invalid project name: ${name}`);
}

function validateKbId(id) {
  if (!/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/.test(id) || !id.includes(".")) fail("KDLC_KB_ID_INVALID", `Invalid knowledge-base ID: ${id}`);
}

export function scaffoldKnowledgeBase({ id, name, title = name, version = "0.1.0" }) {
  validateProjectName(name);
  validateKbId(id);
  const manifest = `api_version: kdlc.dev/v1alpha1\nkind: KnowledgeBase\nmetadata:\n  id: ${quoted(id)}\n  name: ${quoted(name)}\n  title: ${quoted(title)}\n  version: ${quoted(version)}\nformat:\n  type: okf\n  version: \"0.2\"\nprofile: kdlc-base@0.2.0\nownership:\n  owner: ${quoted(`team:${name}`)}\n  maintainers:\n    - ${quoted(`team:${name}`)}\naccess:\n  classification: internal\npublication:\n  stable_requires:\n    human_verifiers: 1\n  default_stale_after: 180d\n`;
  return new Map([
    ["index.md", canonicalText("<!-- generated by kdlc; do not edit -->\n# Knowledge Index")],
    ["knowledge-base.yaml", manifest]
  ]);
}

export function scaffoldProject({ name, title = name, knowledgeBaseId = `local.${name}` }) {
  validateProjectName(name);
  validateKbId(knowledgeBaseId);
  const files = new Map([
    ["knowledge-project.yaml", `api_version: kdlc.dev/v1alpha1\nkind: Project\nmetadata:\n  name: ${quoted(name)}\n  title: ${quoted(title)}\npurpose: ./purpose.md\nprofile: kdlc-base@0.2.0\nknowledge_bases:\n  - name: primary\n    uri: ./knowledge/primary\n    mode: maintain\n    role: primary\n    priority: 100\nrouting:\n  default_write_target: primary\nworkflow:\n  scope: ingest\n  knowledge_depth: standard\n  trust_level: team\n  autonomy: draft\n  approval_policy: publish-only\nretrieval:\n  mode: filesystem\n  default_bases: [primary]\n  minimum_trust: unverified\n  stale_behavior: warn\n  citation_format: qualified\n`],
    ["purpose.md", canonicalText(`# ${title}\n\nDescribe the governed knowledge purpose and scope.`)]
  ]);
  for (const [path, content] of scaffoldKnowledgeBase({ id: knowledgeBaseId, name: "primary", title })) {
    files.set(`knowledge/primary/${path}`, content);
  }
  return new Map([...files].sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0));
}

export async function materializeScaffold(root, files, { overwrite = false } = {}) {
  await mkdir(root, { recursive: true });
  const canonicalRoot = await realpath(root);
  for (const [path, content] of [...files].sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)) {
    const destination = resolve(canonicalRoot, path);
    const rel = relative(canonicalRoot, destination);
    if (isAbsolute(path) || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) {
      fail("KDLC_SCAFFOLD_PATH", `Scaffold path escapes destination root: ${path}`);
    }
    let current = canonicalRoot;
    for (const segment of dirname(rel).split(sep).filter((entry) => entry && entry !== ".")) {
      current = resolve(current, segment);
      try {
        const metadata = await lstat(current);
        if (metadata.isSymbolicLink() || !metadata.isDirectory()) fail("KDLC_SCAFFOLD_PATH", `Unsafe scaffold parent: ${path}`);
      } catch (error) {
        if (error instanceof Error && error.code === "ENOENT") await mkdir(current);
        else throw error;
      }
    }
    if (overwrite) {
      try {
        if ((await lstat(destination)).isSymbolicLink()) fail("KDLC_SCAFFOLD_PATH", `Refusing to overwrite scaffold symlink: ${path}`);
      } catch (error) {
        if (!(error instanceof Error && error.code === "ENOENT")) throw error;
      }
    }
    await writeFile(destination, content, { encoding: "utf8", flag: overwrite ? "w" : "wx" });
  }
  return [...files.keys()].sort();
}
