import { createServer as createHttpServer } from "node:http";
import { createServer as createHttpsServer } from "node:https";

import { KdlcEngine } from "../cli/index.mjs";

export const MCP_PROTOCOL = "2025-06-18";
const toolInputs = {
  project_init: { project_id: "string", title: "string" }, project_get: {}, project_list_mounts: {}, kb_search: { query: "string" }, kb_fetch: { uri: "string" }, kb_trace: { uri: "string" }, kb_conflicts: {}, kb_gaps: {}, source_excerpt: { source_id: "string", locator: "object" }, job_status: { id: "string" },
  ingest_start: { sources: "array", idempotency_key: "string" }, proposal_create: { proposal: "object" }, review_submit: { proposal_id: "string", decision: "string", receipt_id: "string" }, publish_request: { proposal_id: "string", receipt_id: "string", current: "object" }, job_cancel: { id: "string" }
};
const requiredInputs = { kb_search: ["query"], kb_fetch: ["uri"], kb_trace: ["uri"], source_excerpt: ["source_id","locator"], job_status: ["id"], ingest_start: ["sources","idempotency_key"], proposal_create: ["proposal"], review_submit: ["proposal_id","decision","receipt_id"], publish_request: ["proposal_id","receipt_id","current"], job_cancel: ["id"] };
export const MCP_TOOLS = Object.freeze([
  ["project_init","project_init",["mutate"],false],["project_get","status",["read"],true],["project_list_mounts","project_list_mounts",["read"],true],["kb_search","kb_search",["read"],true],["kb_fetch","kb_fetch",["read"],true],["kb_trace","kb_trace",["read"],true],["kb_conflicts","kb_conflicts",["read"],true],["kb_gaps","kb_gaps",["read"],true],["source_excerpt","source_excerpt",["read"],true],["job_status","job_status",["read"],true],
  ["ingest_start","ingest_start",["mutate"],false],["proposal_create","proposal_create",["mutate"],false],["review_submit","review_submit",["review"],false],["publish_request","publish_request",["publish"],false],["job_cancel","job_cancel",["mutate"],false]
].map(([name,operation,scopes,readOnly]) => Object.freeze({ name, operation, scopes, description: `${name} through the governed K-DLC engine`, inputSchema: { type: "object", properties: Object.fromEntries(Object.entries(toolInputs[name]).map(([key, type]) => [key, type === "array" ? { type, items: { type: "string" } } : { type }])), required: requiredInputs[name] ?? [], additionalProperties: false }, annotations: { readOnlyHint: readOnly, destructiveHint: name === "job_cancel", idempotentHint: readOnly || name.endsWith("_start"), openWorldHint: false } })));

function validateToolInput(tool, input) { if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).some((key) => !Object.hasOwn(toolInputs[tool.name], key)) || (requiredInputs[tool.name] ?? []).some((key) => !Object.hasOwn(input, key))) return false; return Object.entries(input).every(([key, value]) => toolInputs[tool.name][key] === "array" ? Array.isArray(value) && value.every((item) => typeof item === "string") : toolInputs[tool.name][key] === "object" ? value !== null && typeof value === "object" && !Array.isArray(value) : typeof value === toolInputs[tool.name][key]); }

export class ServedPrincipalMapper {
  #tokens = new Map();
  constructor(records) { if (!Array.isArray(records)) throw new TypeError("Trusted served principal mappings are required"); for (const record of records) { if (!record || typeof record.token !== "string" || typeof record.actor !== "string" || !Array.isArray(record.scopes) || this.#tokens.has(record.token)) throw new TypeError("Invalid or duplicate served principal mapping"); this.#tokens.set(record.token, { actor: record.actor, scopes: [...new Set(record.scopes)].sort(), issuer: record.issuer ?? null, principal_mode: "served" }); } }
  authenticate(headers) { const authorization = headers?.authorization; if (typeof authorization !== "string" || !authorization.startsWith("Bearer ")) return null; const principal = this.#tokens.get(authorization.slice(7)); return principal ? structuredClone(principal) : null; }
}

export class McpProjectServer {
  constructor({ root, projectId, principal = { actor: "process:local", scopes: ["read","mutate","review","publish"] }, engineFactory = (options) => new KdlcEngine(options) } = {}) { this.root = root; this.projectId = projectId; this.principal = structuredClone(principal); this.engineFactory = engineFactory; }
  engine(principal = this.principal) { return this.engineFactory({ root: this.root, principal }); }
  serverInfo() { return { label: "kdlc", specification_version: "0.2.0", canonicalization: "kdlc-c14n-1", mcp_protocol: MCP_PROTOCOL, transports: ["stdio","streamable-http"], project_id: this.projectId, conformance_modules: ["Core","Lifecycle","Governed","Federated","Served"], format_profiles: ["markdown","text","csv","pdf","docx","xlsx","pptx","drawio","gif","vsdx"], capabilities: { resources: true, tools: true, prompts: false, repository_analysis: false }, tools: MCP_TOOLS.map(({ name }) => name) }; }
  listTools(principal = this.principal) { return MCP_TOOLS.filter((tool) => tool.scopes.every((scope) => principal.scopes.includes(scope))).map(({ operation: ignored, scopes: ignoredScopes, ...tool }) => tool); }
  async resource(uri, principal = this.principal) { if (!principal.scopes.includes("read")) throw Object.assign(new Error("Resource unavailable"), { code: -32003 }); if (uri === "kdlc://server/info") return this.serverInfo(); if (uri === `kdlc://projects/${this.projectId}`) return this.engine(principal).execute("project_get"); if (uri === `kdlc://projects/${this.projectId}/mounts`) return this.engine(principal).execute("project_list_mounts"); const job = /^kdlc:\/\/jobs\/(job_[a-f0-9]{16})$/.exec(uri); if (job) return this.engine(principal).execute("job_status", { id: job[1] }); if (/^kb:\/\/[a-z0-9.-]+\/.+/.test(uri)) return this.engine(principal).execute("kb_fetch", { uri }); const review = /^kdlc:\/\/reviews\/([A-Za-z0-9._-]+)\/packet$/.exec(uri); if (review && this.engine(principal).handlers.review_packet) return this.engine(principal).execute("review_packet", { proposal_id: review[1] }); throw Object.assign(new Error("Resource unavailable"), { code: -32004 }); }
  async request(message, principal = this.principal) { const id = message?.id ?? null; try { let result; if (message?.jsonrpc !== "2.0") throw Object.assign(new Error("Invalid JSON-RPC request"), { code: -32600 }); if (message.method === "initialize") result = { protocolVersion: MCP_PROTOCOL, capabilities: { resources: {}, tools: {} }, serverInfo: { name: "kdlc", version: "0.2.0" } }; else if (message.method === "tools/list") result = { tools: this.listTools(principal) }; else if (message.method === "tools/call") { const tool = MCP_TOOLS.find(({ name }) => name === message.params?.name); if (!tool || !tool.scopes.every((scope) => principal.scopes.includes(scope))) throw Object.assign(new Error("Tool unavailable"), { code: -32004 }); const input = message.params.arguments ?? {}; if (!validateToolInput(tool, input)) throw Object.assign(new Error("Tool input failed schema validation"), { code: -32602 }); const envelope = await this.engine(principal).envelope(tool.operation, input); result = { content: [{ type: "text", text: JSON.stringify(envelope) }], structuredContent: envelope, isError: !envelope.ok }; } else if (message.method === "resources/read") { const value = await this.resource(message.params?.uri, principal); result = { contents: [{ uri: message.params.uri, mimeType: "application/json", text: JSON.stringify(value) }] }; } else if (message.method === "resources/list") result = { resources: [{ uri: "kdlc://server/info", name: "Server information", mimeType: "application/json" }, { uri: `kdlc://projects/${this.projectId}`, name: "Project", mimeType: "application/json" }, { uri: `kdlc://projects/${this.projectId}/mounts`, name: "Mounts", mimeType: "application/json" }] }; else if (message.method === "resources/templates/list") result = { resourceTemplates: [{ uriTemplate: "kb://{knowledge_base_id}/{concept_id}", name: "Knowledge concept", mimeType: "application/json" }, { uriTemplate: "kdlc://jobs/{job_id}", name: "Durable job", mimeType: "application/json" }, { uriTemplate: "kdlc://reviews/{proposal_id}/packet", name: "Review packet", mimeType: "application/json" }] }; else throw Object.assign(new Error("Method not found"), { code: -32601 }); return { jsonrpc: "2.0", id, result }; } catch (error) { return { jsonrpc: "2.0", id, error: { code: error.code ?? -32603, message: error.code === -32004 ? "Resource unavailable" : error.message } }; } }
}

export async function serveStdio(server, { input = process.stdin, output = process.stdout } = {}) { input.setEncoding("utf8"); let pending = ""; for await (const chunk of input) { pending += chunk; let newline; while ((newline = pending.indexOf("\n")) !== -1) { const line = pending.slice(0, newline); pending = pending.slice(newline + 1); if (line.trim()) output.write(`${JSON.stringify(await server.request(JSON.parse(line)))}\n`); } } if (pending.trim()) output.write(`${JSON.stringify(await server.request(JSON.parse(pending)))}\n`); }

export function createStreamableHttpServer({ server, principalMapper, host = "127.0.0.1", tls } = {}) {
  if (!(server instanceof McpProjectServer) || !(principalMapper instanceof ServedPrincipalMapper)) throw new TypeError("HTTP MCP requires a project server and trusted principal mapper");
  if (!tls && !["127.0.0.1","::1","localhost"].includes(host)) throw new TypeError("Non-loopback Streamable HTTP requires TLS");
  const listener = async (request, response) => { const principal = principalMapper.authenticate(request.headers); if (!principal) { response.writeHead(401, { "content-type": "application/json" }); response.end(JSON.stringify({ error: "unauthorized" })); return; } if (request.method !== "POST" || request.url !== "/mcp") { response.writeHead(404); response.end(); return; } let body = ""; for await (const chunk of request) { body += chunk; if (Buffer.byteLength(body) > 1_000_000) { response.writeHead(413); response.end(); return; } } let message; try { message = JSON.parse(body); } catch { response.writeHead(400); response.end(JSON.stringify({ error: "invalid-json" })); return; } const result = await server.request(message, principal); response.writeHead(200, { "content-type": "application/json" }); response.end(JSON.stringify(result)); };
  return tls ? createHttpsServer(tls, listener) : createHttpServer(listener);
}
